### ISSUE TITLE
Using print(dathost.info("server id")) to print one Item.

### ISSUE THREAD

**Issue by WardPearce** [pbexe/dathost-python#1]
Hey,
Random question. How could I print just one item using print(dathost.info("server id")).

e.g. Just server IP.

**Comment by pbexe** [comment]
`dathost.info("server id")` returns a dictionary of attributes of the server. The keys of this dictionary can be found in the [official documentation](https://dathost.net/api#!/default/get_game_server_item).

Just a word of warning, I haven't updated this wrapper in a long time so some functionality may be broken if their API has changed.
