### ISSUE TITLE
Matches missing in dathost class

### ISSUE THREAD

**Issue by MartinH92** [pbexe/dathost-python#2]
Hi, first of all great wrapper you made here.
I'm using it to get data from our Dathost servers to a Raspberry Pi. 
But I really miss being able to get the match information from https://dathost.net/api/0.1/matches/

I have tried to add this myself, but I'm not able to push my branch to your project:
`def match(self, _id):`
        `data = requests.get('https://dathost.net/api/0.1/matches/' + _id)`
        `return json.loads(data.text)`

This is more a request than an issue, but will you add it to your nice service? plleeease 👍 
PS: I'm not sure there's a need for authentication

**Comment by WardPearce** [comment]
Hey,
Not to self promote, but this repository hasn't been updated in 5 years.
Might be worth checking out my wrapper https://github.com/WardPearce/dathost
https://dathost.readthedocs.io/en/latest/

**Comment by MartinH92** [comment]
Oh nice!
Do you know if I can create a match without the entering Steam IDs?
It does not seem like it on Dathosts official documentation, but somehow
eBot and other third party service are able to.

I just want to be able to get information about which team is on CT or T
and track if a player is dead or alive. And apparently I need a match for
that.

Kind regards
Martin Johansen
Chairman in Kolding Esport

Den fre. 18. sep. 2020 kl. 00.41 skrev Ward <notifications@github.com>:

**Comment by WardPearce** [comment]
I'd imagine if you created a match without steam IDs it wouldn't let anyone join.

**Comment by MartinH92** [comment]
That's exactly what happens. But I need an easier way to access players
data on a csgo server.
Creating a match where I need to know the two teams steam IDs seems a
little overkill.

Den lør. 19. sep. 2020 kl. 00.08 skrev Ward <notifications@github.com>:

**Comment by pbexe** [comment]
Hi,
Thanks for having a look at this project. I haven't worked on it in a long time so I would recommend using @WardPearce's  repo instead (https://github.com/WardPearce/dathost). I'll put a deprecation notice up so that others know to go to the other repo.
